# Generated by Django 4.1.7 on 2023-03-14 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание профиля')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('position', models.TextField(max_length=200, null=True, verbose_name='Должность')),
                ('mentor', models.BooleanField(default=False, verbose_name='Является наставником')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'unique_together': {('name', 'surname', 'patronymic')},
            },
        ),
    ]
