# Generated by Django 4.1.7 on 2023-03-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['surname', 'name', 'position'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='mentor',
            field=models.BooleanField(default=True, verbose_name='Является наставником'),
        ),
    ]
