# Generated by Django 4.1.7 on 2023-03-14 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
        ('ks_students', '0011_remove_profile_user_alter_student_id_and_more'),
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions_to_mentor', to='mentor.profile', verbose_name='Наставник'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions_to_status', to='interaction.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions_to_student', to='ks_students.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions_to_type', to='interaction.interactiontype', verbose_name='Тип взаимодействия'),
        ),
    ]
