# Generated by Django 4.1.7 on 2023-03-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_alter_interaction_mentor_alter_interaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
