# Generated by Django 4.1.7 on 2023-03-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_alter_interaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
