# Generated by Django 4.1.7 on 2023-03-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0004_alter_interaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interaction.interactiontype', verbose_name='Тип взаимодействия'),
        ),
    ]
