# Generated by Django 4.1.7 on 2023-03-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0005_alter_interaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiontype',
            name='type_name',
            field=models.CharField(max_length=50, verbose_name='Название типа взаимодействия'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(max_length=50, verbose_name='Название статуса'),
        ),
    ]
