# Generated by Django 4.1.7 on 2023-03-18 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0006_alter_interactiontype_type_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['start_date', 'end_date'], 'verbose_name': 'Взаимодействие', 'verbose_name_plural': 'Взаимодействия'},
        ),
        migrations.AlterField(
            model_name='interaction',
            name='status',
            field=models.ForeignKey(default='Новый', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions_to_status', to='interaction.status', verbose_name='Статус'),
        ),
    ]
