# Generated by Django 4.1.7 on 2023-03-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0008_alter_interaction_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['status', 'start_date', 'end_date'], 'verbose_name': 'Взаимодействие', 'verbose_name_plural': 'Взаимодействия'},
        ),
    ]
