# Generated by Django 4.1.7 on 2023-03-20 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0010_interaction_description_alter_interaction_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 3, 20), null=True, verbose_name='Дата начала'),
        ),
    ]
