# Generated by Django 4.1.7 on 2023-03-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_options_alter_tag_unique_together'),
        ('interaction', '0011_alter_interaction_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='tags',
            field=models.ManyToManyField(to='tags.tag', verbose_name='Технологии(теги)'),
        ),
    ]
