# Generated by Django 4.1.7 on 2023-03-21 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0013_alter_interaction_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 3, 21), null=True, verbose_name='Дата начала'),
        ),
    ]
