# Generated by Django 4.1.7 on 2023-03-21 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0014_alter_interaction_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата начала'),
        ),
    ]
