# Generated by Django 4.1.7 on 2023-03-22 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_students', '0016_alter_student_photo'),
        ('mentor', '0002_alter_profile_options_alter_profile_mentor'),
        ('tags', '0002_alter_tag_options_alter_tag_unique_together'),
        ('interaction', '0015_alter_interaction_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions_to_mentor', to='mentor.profile', verbose_name='Наставник'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='status',
            field=models.ForeignKey(blank=True, default='Новый', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions_to_status', to='interaction.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions_to_student', to='ks_students.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='interactions_by_tag', to='tags.tag', verbose_name='Технологии(теги)'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interaction.interactiontype', verbose_name='Тип взаимодействия'),
        ),
    ]
