# Generated by Django 4.1.7 on 2023-03-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0016_alter_interaction_mentor_alter_interaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Прикрепленный файл'),
        ),
    ]
