# Generated by Django 4.1.7 on 2023-03-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'verbose_name': 'Взаимодействие', 'verbose_name_plural': 'Взаимодействия'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AddField(
            model_name='interaction',
            name='interaction_name',
            field=models.TextField(blank=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
    ]
