# Generated by Django 4.1.7 on 2023-03-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_students', '0003_alter_interaction_interaction_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField(verbose_name='Название типа взаимодействия')),
            ],
            options={
                'verbose_name': 'Тип взаимодействия',
                'verbose_name_plural': 'Типы взаимодействия',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.TextField(verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AlterField(
            model_name='interaction',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ks_students.status'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ks_students.interactiontype'),
        ),
    ]
