# Generated by Django 4.1.7 on 2023-03-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ks_students', '0007_alter_student_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ks_students.profile', verbose_name='Наставник'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ks_students.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ks_students.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ks_students.interactiontype', verbose_name='Тип взаимодействия'),
        ),
    ]
