# Generated by Django 4.1.7 on 2023-03-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_students', '0009_alter_student_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mentor',
            field=models.BooleanField(default=False, verbose_name='Является наставником'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.TextField(max_length=200, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
