# Generated by Django 4.1.7 on 2023-03-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_students', '0012_alter_student_mentor_alter_student_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(choices=[('ЧГУ им. И.Н. Ульянова', 'ЧГУ им. И.Н. Ульянова'), ('Московский политех', 'Московский политех'), ('Прочее', 'Прочее')], max_length=200, verbose_name='Место учебы'),
        ),
    ]
