# Generated by Django 4.1.7 on 2023-03-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_students', '0013_alter_student_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год поступления'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='communication_other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Другие способы коммуникации'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(blank=True, choices=[('ЧГУ им. И.Н. Ульянова', 'ЧГУ им. И.Н. Ульянова'), ('Московский политех', 'Московский политех'), ('Прочее', 'Прочее')], max_length=200, null=True, verbose_name='Место учебы'),
        ),
    ]
