# Generated by Django 4.1.7 on 2023-03-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ks_students', '0015_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото профиля'),
        ),
    ]
